spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  cache:
    type: redis
  redis:
    client-name: my-card-redis
    host: localhost
    port: 6379
    timeout: 60000
    password: redispass
    lettuce:
      pool:
        max-active: 50
        max-idle: 50
        max-wait: 50ms
        min-idle: 0

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

security:
  oauth2:
    resource:
      service-id: my-card-auth
      user-info-uri: http://${security.oauth2.resource.service-id}/user
      loadBalanced: true

logging:
  level:
    org:
      springframework:
        cache: TRACE