hibernate:
  show_sql: true

spring:
  application:
    name: 'cards'
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka